const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('workbench', {
  getOrgAgenda: () => ipcRenderer.invoke('org-agenda:get'),
  diagnostics: () => ipcRenderer.invoke('diagnostics:get'),
  roots: () => ipcRenderer.invoke('roots'),
  parentDirectory: (p) => ipcRenderer.invoke('files:parent', p),
  homeDirectory: () => ipcRenderer.invoke('files:home'),
  getRecentNotes: () => ipcRenderer.invoke('recent-notes:get'),
  listDir: (p) => ipcRenderer.invoke('list-dir', p),
  readFile: (p) => ipcRenderer.invoke('read-file', p),
  readImageData: (p) => ipcRenderer.invoke('read-image-data', p),
  saveFile: (payload) => ipcRenderer.invoke('save-file', payload),
  fileInfo: (p) => ipcRenderer.invoke('file-info', p),
  rename: (payload) => ipcRenderer.invoke('rename', payload),
  trash: (p) => ipcRenderer.invoke('trash', p),
  newFolder: (payload) => ipcRenderer.invoke('new-folder', payload),
  newFile: (payload) => ipcRenderer.invoke('new-file', payload),
  move: (payload) => ipcRenderer.invoke('move', payload),
  reveal: (p) => ipcRenderer.invoke('reveal', p),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  openDefault: (p) => ipcRenderer.invoke('open-default', p),
  exportRenderedPdf: (payload) => ipcRenderer.invoke('export-rendered-pdf', payload),
  newNote: (payload) => ipcRenderer.invoke('new-note', payload),
  toggleOrgLine: (payload) => ipcRenderer.invoke('toggle-org-line', payload),
  buildCommand: (p) => ipcRenderer.invoke('build-command', p),
  homeShortcuts: () => ipcRenderer.invoke('home-shortcuts:get'),
  saveHomeShortcuts: (payload) => ipcRenderer.invoke('home-shortcuts:save', payload),
  generatedOutputs: (payload) => ipcRenderer.invoke('generated-outputs', payload),
  latestGeneratedOutput: (p) => ipcRenderer.invoke('latest-generated-output', p),
  buildLatex: (p) => ipcRenderer.invoke('build-latex', p),
  resolveOrgLink: (payload) => ipcRenderer.invoke('resolve-org-link', payload),

  terminalCreate: (payload) => ipcRenderer.invoke('terminal-create', payload),
  terminalPing: () => ipcRenderer.invoke('terminal-ping'),
  terminalWrite: (payload) => ipcRenderer.invoke('terminal-write', payload),
  terminalResize: (payload) => ipcRenderer.invoke('terminal-resize', payload),
  terminalCwd: (payload) => ipcRenderer.invoke('terminal-cwd', payload),

  onTerminalData: (cb) => ipcRenderer.on('terminal-data', (_e, data) => cb(data)),
  onTerminalExit: (cb) => ipcRenderer.on('terminal-exit', (_e, data) => cb(data)),
  onWorkbenchOpenPath: (cb) => ipcRenderer.on('workbench-open-path', (_e, data) => cb(data)),
  onFsChanged: (cb) => ipcRenderer.on('fs:changed', (_e, data) => cb(data))
});
